services:
  db:
    image: postgres:15
    container_name: uprompt_db
    restart: always
    environment:
      - POSTGRES_USER=uprompt_user
      - POSTGRES_PASSWORD=uprompt_password
      - POSTGRES_DB=uprompt_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: uprompt_backend
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - ./backend/.env

volumes:
  postgres_data: